package com.example.basiclogin.Auth

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import com.example.basiclogin.MainActivity
import com.example.basiclogin.R
import com.example.basiclogin.databinding.ActivityLoginBinding
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.functions.FirebaseFunctions
import com.google.firebase.functions.ktx.functions
import com.google.firebase.ktx.Firebase

class Login : AppCompatActivity() {

    private lateinit var binding: ActivityLoginBinding
    private lateinit var auth: FirebaseAuth
    private lateinit var functions: FirebaseFunctions
    private lateinit var googleSignInClient: GoogleSignInClient

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        auth = FirebaseAuth.getInstance()
        functions = Firebase.functions


        try {
            functions.useEmulator("10.0.2.2", 5001)
            auth.useEmulator("10.0.2.2", 9099)
        } catch (e: Exception) {
            Log.w("Login", "Emulator issue: ${e.message}")
        }

        if (auth.currentUser != null) {
            navigateToMain()
            return
        }

        binding = ActivityLoginBinding.inflate(layoutInflater)
        setContentView(binding.root)

        setupInitialUI()
        setupGoogleSignIn()

        binding.loginbtn.setOnClickListener {
            val email = binding.emlsgnup.text.toString().trim()
            val otp = binding.pwdsgnup.text.toString().trim()

            if (binding.loginbtn.text == "Get Code") {
                if (email.isNotEmpty()) sendOtp(email)
                else binding.emlsgnup.error = "Email required"
            } else {
                if (otp.isNotEmpty()) verifyOtp(email, otp)
                else binding.pwdsgnup.error = "Enter code"
            }
        }


        binding.signinG.setOnClickListener {
            signInWithGoogle()
        }
    }


    private fun setupGoogleSignIn() {
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id)) // Auto-generated by firebase
            .requestEmail()
            .build()

        googleSignInClient = GoogleSignIn.getClient(this, gso)
    }

    private fun signInWithGoogle() {
        val signInIntent = googleSignInClient.signInIntent
        googleSignInLauncher.launch(signInIntent)
    }

    private val googleSignInLauncher = registerForActivityResult(
        ActivityResultContracts.StartActivityForResult()
    ) { result ->
        if (result.resultCode == Activity.RESULT_OK) {
            val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
            try {

                val account = task.getResult(ApiException::class.java)
                firebaseAuthWithGoogle(account.idToken!!)
            } catch (e: ApiException) {
                Log.w("Login", "Google sign in failed", e)
                Toast.makeText(this, "Google Sign-In Failed", Toast.LENGTH_SHORT).show()
            }
        }
    }

    private fun firebaseAuthWithGoogle(idToken: String) {
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        auth.signInWithCredential(credential)
            .addOnSuccessListener {
                Toast.makeText(this, "Google Login Successful!", Toast.LENGTH_SHORT).show()
                navigateToMain()
            }
            .addOnFailureListener { e ->
                Toast.makeText(this, "Firebase Auth Failed: ${e.message}", Toast.LENGTH_SHORT).show()
            }
    }


    private fun setupInitialUI() {
        binding.pwdsgnup.visibility = View.GONE
        binding.textpwd.visibility = View.GONE
        binding.loginbtn.text = "Get Code"
    }

    private fun sendOtp(email: String) {
        binding.loginbtn.isEnabled = false
        binding.loginbtn.text = "Sending..."


        functions.getHttpsCallable("send_email_otp").call(hashMapOf("email" to email))
            .addOnSuccessListener {

                val response = it.getData() as? Map<String, Any>
                if (response?.get("success") == true) {
                    binding.pwdsgnup.visibility = View.VISIBLE
                    binding.textpwd.visibility = View.VISIBLE
                    binding.loginbtn.text = "Verify & Login"
                    binding.loginbtn.isEnabled = true
                }
            }
            .addOnFailureListener {
                binding.loginbtn.isEnabled = true
                binding.loginbtn.text = "Get Code"
            }
    }

    @Suppress("UNCHECKED_CAST")
    private fun verifyOtp(email: String, code: String) {

        functions.getHttpsCallable("verify_email_otp").call(hashMapOf("email" to email, "code" to code))
            .addOnSuccessListener { res ->
                val data = res.getData() as? Map<String, Any>
                val token = data?.get("token") as? String
                if(token != null) signInWithToken(token)
            }
    }

    private fun signInWithToken(token: String) {
        auth.signInWithCustomToken(token)
            .addOnSuccessListener { navigateToMain() }
    }

    private fun navigateToMain() {
        val intent = Intent(this, MainActivity::class.java)
        intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
        startActivity(intent)
        finish()
    }
}